import { assertDatabaseUrl, query } from './postgres.js';

export async function migrate() {
  assertDatabaseUrl();

  await query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('employee', 'approver')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS expense_reports (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_id INTEGER NOT NULL REFERENCES users(id),
      title TEXT NOT NULL,
      period_start TEXT NOT NULL,
      period_end TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'paid'))
        DEFAULT 'draft',
      submitted_at TIMESTAMPTZ,
      archived_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS expense_lines (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      report_id INTEGER NOT NULL REFERENCES expense_reports(id) ON DELETE CASCADE,
      spent_on TEXT NOT NULL,
      amount_cents INTEGER NOT NULL CHECK (amount_cents >= 0),
      category TEXT NOT NULL CHECK (category IN (
        'travel', 'meals', 'supplies', 'lodging', 'other'
      )),
      description TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS report_approvers (
      report_id INTEGER NOT NULL REFERENCES expense_reports(id) ON DELETE CASCADE,
      approver_id INTEGER NOT NULL REFERENCES users(id),
      PRIMARY KEY (report_id, approver_id)
    );

    CREATE TABLE IF NOT EXISTS status_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      report_id INTEGER NOT NULL REFERENCES expense_reports(id) ON DELETE CASCADE,
      old_status TEXT,
      new_status TEXT NOT NULL,
      actor_id INTEGER NOT NULL REFERENCES users(id),
      reason TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS comments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      report_id INTEGER NOT NULL REFERENCES expense_reports(id) ON DELETE CASCADE,
      author_id INTEGER NOT NULL REFERENCES users(id),
      body TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS alert_dismissals (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      report_id INTEGER NOT NULL REFERENCES expense_reports(id) ON DELETE CASCADE,
      approver_id INTEGER NOT NULL REFERENCES users(id),
      dismissed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE (report_id, approver_id)
    );

    CREATE INDEX IF NOT EXISTS idx_reports_owner ON expense_reports(owner_id);
    CREATE INDEX IF NOT EXISTS idx_reports_status ON expense_reports(status);
    CREATE INDEX IF NOT EXISTS idx_reports_submitted ON expense_reports(submitted_at);
    CREATE INDEX IF NOT EXISTS idx_lines_report ON expense_lines(report_id);
  `);
}

export const CATEGORIES = ['travel', 'meals', 'supplies', 'lodging', 'other'] as const;
export type Role = 'employee' | 'approver';
export type Status = 'draft' | 'submitted' | 'approved' | 'rejected' | 'paid';
